# Generated by Django 3.0.8 on 2020-07-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='max_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('oil_change', models.IntegerField()),
                ('airfilter_change', models.IntegerField()),
                ('spark_plug_change', models.IntegerField()),
                ('tire_change', models.IntegerField()),
                ('battery_change', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('mileage', models.IntegerField()),
                ('price', models.IntegerField()),
                ('oil_change', models.IntegerField()),
                ('airfilter_change', models.IntegerField()),
                ('spark_plug_change', models.IntegerField()),
                ('tire_change', models.IntegerField()),
                ('battery_change', models.IntegerField()),
                ('vehicle_image', models.ImageField(upload_to='vehicleapp/static/')),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
